### ISSUE TITLE
Add tag for 2.0

### ISSUE THREAD

**Issue by moderndeveloperllc** [6to5/gulp-6to5#9]
Sorry to be pedantic, but could you add the 2.0.0 release as a tag? Just for reference sake if nothing else. Thanks.

**Comment by sindresorhus** [comment]
Done.

@sebmck Can you use https://gist.github.com/sindresorhus/8435329 or something to do releases? That way this never happens.

**Comment by sebmck** [comment]
@sindresorhus Sure, sorry!

**Comment by sindresorhus** [comment]
No worries. It's very easy to forget (hence tooling) :)
